// frontend/src/features/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { SignupData } from '../../core/models/signup-data';
import { NgFor, NgIf } from '@angular/common';
import { countries } from 'countries-list'
import { AuthService } from '../../core/services/auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  imports: [RouterModule, FormsModule, NgFor, NgIf],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.scss'
})

export class SignupComponent implements OnInit {

  signupData: SignupData = {
    username: '',
    email: '',
    password: '',
    points: 0,
    proficiency: '',
    region: ''
  }

  allCountries: string[] = [];
  filteredCountries: string[] = [];

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {
    this.allCountries = Object.values(countries).map(c => c.name).sort();
  }

  onRegionInput(): void {
    const input = this.signupData.region.toLowerCase();
    this.filteredCountries = this.allCountries.filter(country => country.toLowerCase().startsWith(input));
  }

  selectCountry(country: string): void {
    this.signupData.region = country;
    this.filteredCountries = [];
  }

  onSignup() {
    if (!this.allCountries.includes(this.signupData.region)) {
      return;
    }
    this.authService.signup(this.signupData).subscribe({
      next: () => {
          this.router.navigate(['/login']);
      },
      error: err => {
        console.error('Signup error:', err);
      }
    })
  }
}

<h1>Sign Up</h1>

<form class="form-data" (ngSubmit)="onSignup()">
    <input type="text" placeholder="Username" name="username" [(ngModel)]="signupData.username" required />
    <input type="password" placeholder="Password" name="password" [(ngModel)]="signupData.password" required />
    <input type="email" placeholder="Email" name="email" [(ngModel)]="signupData.email" required />

    <select [(ngModel)]="signupData.proficiency" name="proficiency" required>
        <option value="">Select Level</option>
        <option *ngFor="let level of ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']" [value]="level">{{ level }}</option>
    </select>

    <input type="text" placeholder="Region" name="region" [(ngModel)]="signupData.region" (input)="onRegionInput()" required />

    <ul *ngIf="filteredCountries.length > 0">
        <li
            *ngFor="let country of filteredCountries"
            (click)="selectCountry(country)"
        >
            {{ country }}
        </li>
    </ul>


    <button type="submit">Sign Up</button>
</form>

<p>Have an account? <a routerLink="/login">Login</a></p>

// frontend/src/pages/Signup.jsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { signUpAuth } from "../services/authService";

const Signup = () => {
    const [formData, setFormData] = useState({
        username: "",
        email: "",
        password: "",
        points: 0,
        proficiency: "", 
        region: "", 
    });

    const [countries, setCountries] = useState([]);
    const [filteredCountries, setFilteredCountries] = useState([]);
    const proficiencyLevels = ["A1","A2","B1","B2","C1","C2"];
    const navigate = useNavigate();
    const [regionErr, setRegionErr] = useState("");

    useEffect(() => {
        fetch("https://restcountries.com/v3.1/all")
        .then((response) => response.json())
        .then((data) => {
            const countryNames = data.map((country) => country.name.common);
            countryNames.sort();
            setCountries(countryNames);
        })
        .catch((error) => console.error("Error fetching countries:", error));
    }, [])

    const handleChange = (e) => {
        const { name, value } = e.target;

        if (name === "region") {
            const filtered = countries.filter((country) =>
                country.toLowerCase().startsWith(value.toLowerCase())
            );
            setFilteredCountries(filtered);
        }

        setFormData({
            ...formData,
            [name]: value,
        });
    }

    const handleSignup = async (e) => {
        e.preventDefault();

        if (!countries.includes(formData.region)) {
            setRegionErr("Please select a valid country from the list.");
            return;
        }
        setRegionErr("");
        
        try {
            console.log("Info: ",JSON.stringify(formData))
            await signUpAuth(formData);
            
            //alert("Account created successfully!");
            setFormData({
                username: "",
                email: "",
                password: "",
                points: 0,
                proficiency: "",
                region: "",
            });
            navigate("/login");
        } catch (err) {
            console.error("Error during signup: ",err);   
         //   alert("An error occurred, please try again,");
        }
            
    }

    return (
        <>
            <h1>Sign Up</h1>
            
            <form onSubmit={handleSignup}>
                <div className="user-info">
                <div>
                    <label>Region: </label>
                        <input
                            type="text"
                            id="region"
                            name="region"
                            value={formData.region}
                            onChange={handleChange}
                            placeholder="Search for a Country"
                            required
                        />
                        {filteredCountries.length > 0 && (
                            <ul>
                                {filteredCountries.map((country) => (
                                    <li
                                        key={country}
                                        onClick={() => {
                                            setFormData({ ...formData, region: country });
                                            setFilteredCountries([]);  
                                        }}
                                    >
                                        {country}
                                    </li>
                                ))}
                            </ul>
                        )}
                        {regionErr &&
                            <p>{regionErr}</p>
                        }
                    </div>

                    <div>
                        <label>Proficiency: </label>
                        <select 
                            id="proficiency"
                            name="proficiency"
                            value={formData.proficiency}
                            onChange={handleChange}
                            required 
                        >
                            <option>Select CEFR Level</option>
                            {proficiencyLevels.map((level) => (
                                <option key={level} value={level}>
                                    {level}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div>
                       <label>Points: 0</label>
                    </div>
                </div>

            <div className="login-info">
                    <div>
                        <label>Username: </label>
                        <input 
                            type="text"
                            id="username"
                            name="username"
                            value={formData.username}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    <div>
                        <label>Email: </label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            value={formData.email}
                            onChange={handleChange}
                            required
                        />
                    </div>

                    <div>
                        <label>Password: </label>
                        <input
                            type="password"
                            id="password"
                            name="password"
                            value={formData.password}
                            onChange={handleChange}
                            required
                        />
                    </div>
                </div>
                <button type="submit">Sign Up</button>
            </form>
        </>
    );
}


export default Signup
